### ISSUE TITLE
Provide build instructions please?

### ISSUE THREAD

**Issue by dmontauk** [vadims/gerrit-owners#6]
I've spent an hour trying to figure out how to build this plugin. Here's what hasn't worked:

$ git clone https://github.com/vadims/gerrit-owners.git && cd gerrit-owners && buck build gerrit-owners:owners
<snip>
IOError: [Errno 2] No such file or directory: '/home/ubuntu/gerrit-owners/plugins/gerrit-owners/common.defs'

I've tried moving files around, building from the plugins dir, etc. Any advice on how to build this from scratch?

**Comment by dmontauk** [comment]
I'm making some progress so documenting it here.
1. You need to build from within the Gerrit tree. 
2. You can't use master/HEAD since they've changed stuff that breaks the build.

This assumes that you have buck available. If you don't, follow these instructions here: 
https://gerrit-review.googlesource.com/Documentation/dev-buck.html#_installation

git clone --recursive https://gerrit.googlesource.com/gerrit
git fetch origin stable-2.11:stable-2.11
git checkout stable-2.11
cd gerrit
buck build gerrit
cd gerrit/plugins
git clone https://github.com/vadims/gerrit-owners.git
cd ..
buck build plugins/gerrit-owners/gerrit-owners:owners

Currently building so I'll update this if it works...

**Comment by dmontauk** [comment]
Things are still not working. Plugin list:

Plugin Name	Settings	Version	Status
commit-message-length-validator		v2.10	Enabled
download-commands		v2.10	Enabled
gerrit-oauth-provider		2.11	Enabled
gravatar-avatar-provider		1.0-SNAPSHOT	Enabled
owners		v2.11.2-27-g8837269	Enabled
owners-autoassign		v2.11.2-27-g8837269	Enabled

So that looks good... But when I test the rule:
$ cat rules.pl | ssh gerrit -p 29418 gerrit test-submit rule -s I9f4604bfdfee16eecdcd977a598237e30d25a4b6
fatal: internal server error

With this rule:
  submit_rule(S) :-
      gerrit:default_submit(D),
      D =.. [submit | Ds],
      findall(U, gerrit:commit_label(label('Code-Review', 2), U), Approvers),
      gerrit_owners:add_owner_approval(Approvers, Ds, A),
      S =.. [submit | A].

**Comment by dmontauk** [comment]
2015-08-07 11:59:23,187] ERROR com.google.gerrit.sshd.BaseCommand : Internal server error (user dobromir account 113) during gerrit test-submit rule -s I9f4604bfdfee16eecdcd977a598237e30d25a4b6
java.lang.NoSuchMethodError: org.eclipse.jgit.revwalk.RevWalk.release()V
	at org.gitective.core.CommitUtils.parse(CommitUtils.java:352)
	at org.gitective.core.BlobUtils.getRawContent(BlobUtils.java:192)
	at org.gitective.core.BlobUtils.getContent(BlobUtils.java:246)
	at com.vmware.gerrit.owners.common.PathOwners.getOwners(PathOwners.java:149)
	at com.vmware.gerrit.owners.common.PathOwners.fetchOwners(PathOwners.java:71)
	at com.vmware.gerrit.owners.common.PathOwners.<init>(PathOwners.java:49)
	at com.vmware.gerrit.owners.OwnersStoredValues$1.createValue(OwnersStoredValues.java:44)
	at com.vmware.gerrit.owners.OwnersStoredValues$1.createValue(OwnersStoredValues.java:35)
	at com.google.gerrit.rules.StoredValue.get(StoredValue.java:64)
	at gerrit_owners.PRED_owner_path_1.exec(PRED_owner_path_1.java:38)

So tracking that down...

**Comment by dmontauk** [comment]
gerrit-owners has:
maven_jar(
  name = 'gitective-core',
  id = 'org.gitective:gitective-core:0.9.9',
  license = 'Apache2.0',
)

gitective-core (no longer maintained) has:
		<dependency>
			<groupId>org.eclipse.jgit</groupId>
			<artifactId>org.eclipse.jgit</artifactId>
			<version>2.0.0.201206130900-r</version>
		</dependency>

gerrit 2.11 has lib/jgit/BUCK:
  3 REPO = MAVEN_CENTRAL # Leave here even if set to MAVEN_CENTRAL.
  4 VERS = '4.0.1.201506240215-r'
  5
  6 maven_jar(
  7   name = 'jgit',
  8   id = 'org.eclipse.jgit:org.eclipse.jgit:' + VERS,
  9   bin_sha1 = '3bdf2d666df1a5373f7ad291c075ab1329560afd',
 10   src_sha1 = 'c8ab3011612a4680791df394e2ef1ab8debeaed6',
 11   license = 'jgit',
 12   repository = REPO,
 13   unsign = True,
 14   deps = [':ewah'],
 15   exclude = [
 16     'META-INF/eclipse.inf',
 17     'about.html',
 18     'plugin.properties',
 19   ],
 20 )

RevWalk in gerrit-owner reqs:
http://download.eclipse.org/jgit/docs/jgit-2.0.0.201206130900-r/apidocs/org/eclipse/jgit/revwalk/RevWalk.html

Release method is missing in new version:
http://git.eclipse.org/c/jgit/jgit.git/tree/org.eclipse.jgit/src/org/eclipse/jgit/revwalk/RevWalk.java

**Comment by dmontauk** [comment]
I ripped out all the dependencies on gitective (copy/pasted them into gerrit-owners) and renamed the .release() to .close(). Things work now.

I'll issue a pull request with the instructions above + working code so the next user doesn't have to spend 6 hours getting it working ;)

**Comment by vadims** [comment]
I'm sorry about the compilation issues. I haven't been actively maintaining this project because I no longer use Gerrit, however I'm happy to accept any PR to fix the build/update docs/etc.

**Comment by garethbowles** [comment]
@dmontauk I just ran into this problem, thanks a bunch for the write up.  Could you send the pull request, or maybe attach the changes here ?

**Comment by dmontauk** [comment]
Sorry, been behind on that. Let me try to get it working tomorrow.

**Comment by garethbowles** [comment]
Thanks !  A couple of pointers should be enough to get me going - what did you replace org.gitective.core.BlobUtils with in PathOwners.java, and where is the call to RevWalk.release() ? (I couldn't find it when searching the plugin code or the Gerrit core).

**Comment by dmontauk** [comment]
https://github.com/tellapart/gerrit-owners/commit/08fcb1aa061fc74e79bba8c69c57871830aec3ea

Let me know if that works and I'll initiate a PR back here.

**Comment by garethbowles** [comment]
Looks great, just a one liner missing: https://github.com/garethbowles/gerrit-owners/commit/8dd4af200f82869c7f3d2649cff192cacbdafdc0

This definitely fixes the NoSuchMethodError exception; I still need to do some testing with different owners files.

Thanks again for the fix !

**Comment by garethbowles** [comment]
Testing worked out fine - this is going to be really useful for us.  Thanks everyone for the work on this.

**Comment by vadims** [comment]
@dmontauk do you want to send a PR?

**Comment by lucamilanesio** [comment]
@vadims why don't we migrate the project to gerrit-review.googlesource.com and build it on gerrit-ci.gerritforge.com? People will then be able to get the CI status immediately, your plugin will be in the official list of Gerrit plugins and builds available in real-time :-)

**Comment by dpursehouse** [comment]
Also if it's on gerrit-review it can be included in the [nightly builds at builds.quelltextlich.at](http://builds.quelltextlich.at/gerrit/nightly/index.html).    Christian is usually pretty quick to upload fixes for build breakages :)

**Comment by lucamilanesio** [comment]
@vadims @dpursehouse *AND* your changes / reviews are getting automatically notified to the Gerrit contributors for review, much easier to get feedback and know what's going on :smile_cat:

**Comment by vadims** [comment]
@lucamilanesio sounds good to me

**Comment by lucamilanesio** [comment]
@vadims thanks for your feedback, could you piggy-back on https://groups.google.com/forum/#!topic/repo-discuss/3I1fxIlPxKA so that we can get the balls rolling?

**Comment by lucamilanesio** [comment]
@vadims the new "home" Git repository has been created https://gerrit-review.googlesource.com/#/admin/projects/plugins/owners. You can sign-in and create your account to be then configured as owner.

**Comment by lucamilanesio** [comment]
@vadims I've submitted a change for building the plugin https://gerrit-review.googlesource.com/#/c/71878/ and tested on Gerrit-CI for stable-2.10 (https://gerrit-ci.gerritforge.com/job/plugin-owners-stable-2.10/) and stable-2.11 (https://gerrit-ci.gerritforge.com/job/plugin-owners-stable-2.11/). It does not build on master yet ...

**Comment by copumpkin** [comment]
:+1: :+1: :+1: 

We also wasted a decent amount of time trying to track down that internal server error problem before we found this thread.

**Comment by itskalai** [comment]
Thanks, I spent quite some time on the 500 server error too! :( Has anyone tried using a gerrit group in the OWNERS file? Is that supported? That way I don't have to edit the file often.

**Comment by dark** [comment]
I too had to find this thread to fix 500 server errors and the NoSuchMethodError exception.
I have stacked all the patches I needed to make this plugin work on Gerrit v2.10 here: dark@fe8622b4790ab9a2087c1e57c5d3581f7cf715bb
